### ISSUE TITLE
Add global configuration file to store common parameters

### ISSUE THREAD

**Issue by andystanton** [docker-exec/dexec#56]
I almost always use the latest C++ with dexec, so rather than having to type this every time:

```sh
$ dexec -b -std=c++14 source.cpp
```

I'd rather just have a `.dexecrc` file in my user home which contained something like:

```yaml
---
c++:
    build-args:
        - -std=c++11
---
```
